server:
  port: 3000
  
db:
  port: 3306
  database: 'ellispace-practice'
  host: 'localhost'
  username: 'root'
  password: 'test'
  synchronize: true

jwt:
  access_secret: 'accessTest'
  access_expiresIn: '30s'
  refresh_secret: 'refreshTest'
  refresh_expiresIn: '7d'